### ISSUE TITLE
Failed Mount:  Failed to mount export brick fstype=xfs

### ISSUE THREAD

**Issue by boconnell2210** [kadalu/kadalu#211]
OS: `CentOS Linux release 7.7.1908 (Core)`
kubectl version: `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3"`
kadalu version: `0.6.0`

### Description:
Fresh install of OS/Kubernetes using kadula to provide storage from a block device, /dev/sdb, the storage pod is not starting properly.  

### Details
logs:
kubectl logs -n kadalu server-storage-pool-1-node1-0-0 glusterfsd
```
+ pid=0
+ cmd=/usr/bin/python3
+ script=/kadalu/server.py
+ trap 'kill ${!}; term_handler' SIGTERM
+ pid=6
+ /usr/bin/python3 /kadalu/server.py
+ true
+ wait 7
+ tail -f /dev/null
[2020-03-05 14:40:00,744] ERROR [glusterfsd - 125:create_and_mount_brick] - Failed to mount export brick	 fstype=xfs device=/dev/sdb mountdir=/bricks/storage-pool-1/data error=[32]  mount: /bricks/storage-pool-1/data: wrong fs type, bad option, bad superblock on /dev/sdb, missing codepage or helper program, or other error.
++ kill 7
++ term_handler
++ '[' 6 -ne 0 ']'
++ kill -SIGTERM 6
/kadalu/startup.sh: line 12: kill: (6) - No such process
++ wait 6
++ exit 143
```
kubectl get pod -n kadalu
```
NAME                              READY   STATUS    RESTARTS   AGE
csi-nodeplugin-ll5z5              3/3     Running   3          34h
csi-provisioner-0                 4/4     Running   4          34h
operator-b85bf6cfb-j8pwl          1/1     Running   1          34h
server-storage-pool-1-node1-0-0   1/2     Running   238        21h
```

kubectl logs -n kadalu csi-provisioner-0 --all-containers
```
[2020-03-05 15:02:34.851884] W [fuse-bridge.c:3878:fuse_statfs_resume] 0-glusterfs-fuse: 42223: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2020-03-05 15:02:36.084861] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-storage-pool-1-client: DNS resolution failed on host server-storage-pool-1-node1-0-0.storage-pool-1
[2020-03-05 15:02:36.853815] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2020-03-05 15:02:36.853911] W [fuse-bridge.c:3878:fuse_statfs_resume] 0-glusterfs-fuse: 42224: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2020-03-05 15:02:38.856445] W [fuse-resolve.c:125:fuse_resolve_gfid_cbk] 0-fuse: 00000000-0000-0000-0000-000000000001: failed to resolve (Transport endpoint is not connected)
[2020-03-05 15:02:38.856570] W [fuse-bridge.c:3878:fuse_statfs_resume] 0-glusterfs-fuse: 42225: STATFS (00000000-0000-0000-0000-000000000001) resolution fail
[2020-03-05 15:02:39.098053] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-storage-pool-1-client: DNS resolution failed on host server-storage-pool-1-node1-0-0.storage-
```

**Comment by amarts** [comment]
@boconnell2210 Multiple things in this issue. 

This is a common error of formatting disk. We couldn't automatically do it, because if user provides a wrong (ie, a disk with data) to kadalu by mistake, we would overwrite/format the data. So, decided to keep it non-automatic.

Now to figure out why the disk is giving error, can you check below?

`lsblk` & `fdisk -l /dev/sdb` ??

I think this is a new disk, and if you are sure about it, you can consider doing below and checking it again too.

`wipefs -a -t dos -f /dev/sdb`

**Comment by boconnell2210** [comment]
Yes, it is a new disk.  I can run wipefs again.

Here are the results of the commands run:
```
[root@node1 ~]# lsblk
NAME                    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                       8:0    0 1000G  0 disk
├─sda1                    8:1    0  500M  0 part /boot
└─sda2                    8:2    0  899G  0 part
  ├─turbo-root          253:0    0   55G  0 lvm  /
  ├─turbo-tmp           253:1    0    2G  0 lvm  /tmp
  ├─turbo-var           253:2    0   40G  0 lvm  /var
  ├─turbo-var_lib_mysql 253:3    0  800G  0 lvm  /var/lib/mysql
  └─turbo-usr_local_bin 253:4    0    2G  0 lvm  /usr/local/bin
sdb                       8:16   0  250G  0 disk
sr0                      11:0    1 1024M  0 rom
[root@node1 ~]# fdisk -l /dev/sdb

Disk /dev/sdb: 268.4 GB, 268435456000 bytes, 524288000 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```

**Comment by amarts** [comment]
Thanks @boconnell2210 

I guess, we need 2 things as next step.

### 1. Code changes

 We can use a new field along with node and device in 'storage' section of storage config, called 'force_format', if present, we can add `-f` (ref: man mkfs.xfs) when the error is bad fs type.

#### what needs to be done:

This needs changes in `operator/main.py` code to add an option to storage section. Pass it as variable through server.yaml template, and depending on the variable handle this in `server/glusterfsd.py`. Try mkfs.xfs like now, and in failure section add one more if case, and compare error string. If its above, do one more try of mkfs.xfs with -f option.

Also, need to provide a flag in CLI to add this as an option to --device option, like `--format=yes`, and add it with right format to storage config yaml file.

### 2. Fail the storage pod

Ideally, when this happens (with or without above fix), we should make sure the whole pod is down. That way, we are sure when debugging the storage pod is the issue, instead of suspecting DNS/network etc etc.

**Comment by boconnell2210** [comment]
As I am finally getting back to this, I wanted to update this on the steps to get this to work.  As of version kubectl-kadalu==0.7.0, this was not done automatically.

Before installing kadalu:

```
sudo wipefs -a -t dos -f /dev/sdb
sudo mkfs.xfs /dev/sdb
sudo init 6 # might not be necessary, but figured it can't hurt

# As in the install guide
sudo pip3 install kubectl-kadalu
kubectl kadalu install
kubectl kadalu storage-add storage-pool1 --type=Replica1 --device node1:/dev/sdb

# Changed the default Storage Class to replica1 (as I am on a single node)
kubectl patch storageclass kadalu.replica1  -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
kubectl patch storageclass kadalu  -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
```

**Comment by amarts** [comment]
Thanks @boconnell2210 ! Looks like this is one of the most common errors which we have encountered so far! Will add this as part of documentation itself.
