### ISSUE TITLE
[RFC] About "stripe" mode

### ISSUE THREAD

**Issue by binali-rustamov** [kadalu/kadalu#215]
Is there mode to enable striping in Kadalu? 

I'm creating a k8s development cluster, and I want to have get disk capacity than HA.

**Comment by amarts** [comment]
Few questions: 

1. Is your single PV size bigger than a single disk/storage backend?

2. Is the storage attached to k8s cluster? Or you want to have it outside?

**Comment by binali-rustamov** [comment]
> Few questions:
> 
>     1. Is your single PV size bigger than a single disk/storage backend?
> 
Yes. For example I have three nodes, each node has a disk with 300Gb capacity. I want to create volume with 400Gb capacity. 
>     2. Is the storage attached to k8s cluster? Or you want to have it outside?
I want to use it inside k8s cluster. Only for development  :)

I had "ResourceExhausted" problem, and I don't know how to fix it.

**Comment by amarts** [comment]
Ok! We had thoughtfully avoided this usecase in our initial versions, mainly because we had seen in our experience most of the times, PV sizes requested were smaller than the underlaying disk/storage size.

> I had "ResourceExhausted" problem, and I don't know how to fix it.

It is expected when your storage is not available (ie, when the size is more than available size).

I don't see ourself working on this feature immediately, mainly because we now get >4TB of Block storage through EBS/AKS/GCP etc... And on physical on-premise setup you can have bigger disks, or even setup RAID/LVM to get larger storage.

While this is not present now, this is possible to achieve with 'Shard' feature:

Here is how to fix it:

1. Add a new set of template files to include 'shard', (server/brick volfile looks same, only client volfile changes).
2. Make sure in your client template, have a jinja2 syntax to have a loop for number of storage to be passed, and later, their volume names to be added to distribute xlator.

3. Create another storage class, and use these template files to be used when that storage class is used.

4. Handle this new storage-config in operator code, and pass it to config map with relevant flags.

To get an idea of how to add a new template, config type, check #160 #37
