### ISSUE TITLE
Suggestion to use volumeBindingMode: WaitForFirstConsumer

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [kadalu/kadalu#251]
From #general on Slack

> Why not to use volumeBindingMode: WaitForFirstConsumer in the StorageClass to ensure the pv will be at the same node of the pod ?
> Currently node_affinity in Kadalu does not help me since i am using StatefulSets application with dynamic volumes creation (volumeClaimTemplates) and you can not use different StorageClass in the same StatefullSet object

More detail - https://kubernetes.io/docs/concepts/storage/storage-classes/ 

The volumeBindingMode field controls when volume binding and dynamic provisioning should occur.

By default, the Immediate mode indicates that volume binding and dynamic provisioning occurs once the PersistentVolumeClaim is created. For storage backends that are topology-constrained and not globally accessible from all Nodes in the cluster, PersistentVolumes will be bound or provisioned without knowledge of the Pod’s scheduling requirements. This may result in unschedulable Pods.

A cluster administrator can address this issue by specifying the WaitForFirstConsumer mode which will delay the binding and provisioning of a PersistentVolume until a Pod using the PersistentVolumeClaim is created. PersistentVolumes will be selected or provisioned conforming to the topology that is specified by the Pod’s scheduling constraints. These include, but are not limited to, resource requirements, node selectors, pod affinity and anti-affinity, and taints and tolerations.

The following plugins support WaitForFirstConsumer with dynamic provisioning:

AWSElasticBlockStore
GCEPersistentDisk
AzureDisk
The following plugins support WaitForFirstConsumer with pre-created PersistentVolume binding:

All of the above
Local

**Comment by AlexisDucastel** [comment]
I think there is no need about WaitForFirstConsumer. This PVC provisioning parameter is only useful when it can have an impact on storage location. But in Kadalu, bricks are provided at installation and storage will be served from :
- node-bounded bricks pods for devices option
- node-bounded bricks pods for hostPaths option
- cluster bounded pod using a PVC for PVC option

In all cases, no need to wait for consuming pod to be scheduled because the storage serving location will not be different wherever the pod will be scheduled on.

As Kadalu PVC are just folders in Gluster volume, Immediate volumeBindingMode is good.

**Comment by aviorma** [comment]
Currently `node_affinity` in Kadalu does not help me since i am using `StatefulSets` application with dynamic volumes creation (volumeClaimTemplates) and you can not use different StorageClass in the same `StatefulSets` object

how do you think we can overcome this ?

**Comment by AlexisDucastel** [comment]
@aviorma I'm sorry but I suppose that your question is not related to this issue, is it ?

Anyway, no you can't set multiple storage class for your statefulset.

**Comment by aravindavk** [comment]
> Currently node_affinity in Kadalu does not help me since i am using StatefulSets application with dynamic volumes creation (volumeClaimTemplates) and you can not use different StorageClass in the same StatefulSets object

> how do you think we can overcome this ?

Please share an example StatefulSet with a dynamic volume template. I will try to find an alternate solution based on the template.

**Comment by aravindavk** [comment]
@aviorma got it. https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/

I need to see if CSI controller can understand from which node request is coming from. I will update you

**Comment by AlexisDucastel** [comment]
> @aviorma got it. https://kubernetes.io/blog/2019/04/04/kubernetes-1.14-local-persistent-volumes-ga/
> 
> I need to see if CSI controller can understand from which node request is coming from. I will update you

Local persistent volumes is not CSI related, it is related to the opportunity to have a "hostPath" equivalent for multiple nodes clusters. 

Moreover, by using Kadalu in replica3 mode, kadalu gluster pods have to be scheduled before to provide a folder in its volume, so what impact would it have to know the PVC requestion pod location ?

**Comment by aravindavk** [comment]
@AlexisDucastel The use case from @aviorma is very simple. Using Kadalu Replica 1 volume as alternative to Local storage. In Kadalu v0.7, we introduced `node_affinity` filter which can be added to Storage Class creation. For example, three nodes available and each node is having one device. Create 3 Kadalu Replica 1 volumes and create respective Storage class with node_affinity set. So if a Pod requires dynamic storage from local node, then it can claim using the respective node's storage class.

But in this case, PV claim is defined in StatefulSet definition itself. When k8s starts StatefulSet in respective node, the requirement is to get PV from the respective node's Kadalu Storage.

As you mentioned, none of these parameters(WaitForFirstConsumer or VolumeNodeAffinity) coming to CSI controller since these are not defined in the CSI spec(https://github.com/container-storage-interface/spec/blob/master/spec.md)

**Comment by AlexisDucastel** [comment]
> @AlexisDucastel The use case from @aviorma is very simple. Using Kadalu Replica 1 volume as alternative to Local storage. In Kadalu v0.7, we introduced `node_affinity` filter which can be added to Storage Class creation. For example, three nodes available and each node is having one device. Create 3 Kadalu Replica 1 volumes and create respective Storage class with node_affinity set. So if a Pod requires dynamic storage from local node, then it can claim using the respective node's storage class.

Okay, but that is in fact the use case for EphemeralStorage or LocalPersistentStorage. really not sure that kadalu should handle this.
