### ISSUE TITLE
RFE: PV resize support (through CSI module)

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#45]
Decide and design possible resize feature.

Will add more details soon. Ping here if you are interested to pick it up

**Comment by hetii** [comment]
I think resizing is one of bit advantage in glusterfs.
As far as I know heketi do it by changing LVM size and apply it in fly, so there is no need to even restart pod that use it. I would love to see similar functionality in kadalu.

**Comment by aravindavk** [comment]
For RWX volumes instead of comparing the Quota already set, compare with the requested quota set size https://github.com/kadalu/kadalu/blob/master/server/quotad.py#L63

```
If new_size > existing_size {
     # Set Quota if free_size_on_disk > (new_size - existing_size)
}

if new_size < existing_size {
     # Set Quota if new_size > du(volume_dir)
}
```

Resizing RWO volumes TBD.

**Comment by amarts** [comment]
For RWO volumes, do something like below (pseudo code):

```
current_size=$(stat -c %s $rwo_filename);
if $new_size_asked > $current_size {
   truncate -s $new_size_asked $rwo_filename;
}

if $new_size_asked < $current_size {
    error_msg;
}
```

And do below on the 'nodeserver' (or wherever we have access to the mount-point)

`xfs_growfs -d $PV_MOUNTPOINT`

**Comment by aravindavk** [comment]
We can split this issue into two separate issues and plan to close RWX resize by v0.6

**Comment by amarts** [comment]
relevant issue! We need pv resize!

**Comment by aviorma** [comment]
any updates?

**Comment by aravindavk** [comment]
> any updates?

Added to v0.8 milestone. Any specific use case in mind? So that it will be useful for our testing.

**Comment by aviorma** [comment]
Very simple use case - Patch and update existing PVC with larger size will extend the glusterfs volume 

StorageClass should has `allowVolumeExpansion: true`
https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/

**Comment by schmitch** [comment]
currently I stumbled at this project and basically I think kadalu should support the following (btw. I'm already stunned how smooth it works, compared to gluster-kubernetes or heketi):

- resizing the underlying device/path **and** especially the pvc, I think for many applications it's especially useful to actually use kadalu to create a `ReadWriteMany` `pvc` around existing gcloud/aws/azure/etc `pvc`'s, however to be flexible it would be useful to start, with say 100Gib and scale higher if needed (cloud storage is not that cheap).
  actually resizing the underlying pvc/device would be needed for local **and** cloud systems and I think when manually using `xfs_growfs` it might already work, it's just not automated, which is probably more useful for cloud environments.
  however since local environments can use a local-provisioner that actually exposes a PV so it can be used with kadalu might make it feasible for local environments aswell.
- it might be also useful to than scale the overlay pvc, since of course your application now demands more storage

**Comment by amarts** [comment]
Thanks @schmitch @aviorma for feedback.
