### ISSUE TITLE
Implement Quota RPC/ReST API in sidecar container of server pods

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#5]
When subdirectory is created with required size, Xfs(or respective FS) Quota need to be set in each bricks backend.

**Comment by aravindavk** [comment]
To do any required operation in server pods. For example, set backend quota or to get status of Self heal etc.

## Managing directory Quota
- When a directory is created, set Quota for requested size.
- When Quota resize is requested:
    - If requested size is more than existing quota size, then check for available size in brick path. Error if space is not available.
    - If requested size is less than the existing quota size, Set new Quota value only if directory used size is less than requested quota size. 
- Delete Quota is not required since directory will be deleted.

For each PV create request,

- Mount the hosting Volume if not exists
- Choose hosting Volume from multiple hosting Volumes(based on required space)
- Create sub directory
- Send RPC call to each agent service(In each server pods of respective hosting Volume)

### Problems:

- If a server pod is not reachable, Volume creation will fail.

### Alternate solution:

Instead of creating RPC service, create sidecar container to watch for new directory creation or modification(by crawling) and set quota accordingly.

Only disadvantage I can think of is delay in setting Quota. If application over uses full space before quota is set then it can cause problem.

@amarts @sac any other suggestions?

**Comment by amarts** [comment]
Thanks for this. I am of the opinion to implement the sidecar model for now.

This helps in quickest, and simplest implementation. We can track failed call separately, and may be do it again once in every 10mins or something like that. I don't see a huge problem with that to 'start' with.

**Comment by amarts** [comment]
Update: PR #23 does implement some part of this.

We have chosen the way to do this, mainly because this doesn't involve another web 'service', and is fool proof. Mainly because this is inside glusterfs, which can get self-healed even when it goes out of sync. As the 'info' file is in same gluster volume as that of PV (PersistentVolume), it works similar to glusterfs's xattr model. We do have metadata, but it is with data itself. This way, we avoid another place to keep the source of truth.

Quota is set by the sidecar, and it will currently handle xfs quota only.

**Comment by aravindavk** [comment]
PR #23 implemented this. Sidecar container watches for new directory in brick mount and sets quota as required.
