### ISSUE TITLE
Do we have a troubleshooting guide ?

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#628]
Thanks for the help over the slack channel, but I was thinking of updating the kadalu troubleshooting guide (or create some) with common problems.

For example the following was quite helpful to identify my issue with external volume and gluster's quota:
```
kubectl exec -it kadalu-csi-provisioner-0 -c kadalu-provisioner -- sh -c 'df -h | grep -P secret-volume; echo $SECRET_GLUSTERQUOTA_SSH_USERNAME'
```

**Comment by leelavg** [comment]
@hunter86bg good to hear that the issue is finally resolved. 

We are always trying to keep docs in sync with code, blogging in Kadalu website and other platforms as everything can't fit in docs.

We do this so users can make educated guess when things go wrong with available info.

Yes, you can add above info [here](https://github.com/kadalu/kadalu/blob/devel/doc/troubleshooting.adoc). When you do so, pls specifically mention, it's for external gluster native quota.

The only reason for not adding all the tid bits is, these can be kinda gotchas and due care should be taken/explained to convey full picture which may be hard at times (specifically when data is at stake 😅)

I was also of same opinion until recently but realised too much info might confuse users as well.

PS: These are only my thoughts 😀, maintainers may have a different opinion, will wait for their comments.

**Comment by hunter86bg** [comment]
https://github.com/kadalu/kadalu/pull/657 should add that info
