### ISSUE TITLE
Upgrade options?

### ISSUE THREAD

**Issue by joelcwe** [kadalu/kadalu#646]
Is there a guide on how to upgrade from an older deployment of kadalu?

**Comment by amarts** [comment]
(Credits to @ Thomas Lecavelier on Slack)

----
# Kadalu upgrade
​
## Context
​
k8s cluster managed with Rancher2 (2.4.15) , 11 nodes k8s v1.18, 3 nodes with kadalu disks.
Kadalu installed via kubectl-kadalu. Upgrade from v0.8.1 to v0.8.6.
14 kadalu managed PVs mounted for more than 700Gb (each from 1Gb to 200Gb)
​
## Steps
​
1. Replace kubectl-kadalu with v0.8.6
​
```
  curl -LO https://github.com/kadalu/kadalu/releases/download/0.8.6/kubectl-kadalu
  chmod +x ./kubectl-kadalu
  sudo mv ./kubectl-kadalu /usr/local/bin/kubectl-kadalu
  kubectl-kadalu version
​
  => kubectl-kadalu 0.8.6
```
​
2. Apply the kadalu operator file: https://raw.githubusercontent.com/kadalu/kadalu/0.8.6/manifests/kadalu-operator.yaml (optionnaly turn the verbosity to "yes")
​
```
curl -s https://raw.githubusercontent.com/kadalu/kadalu/0.8.6/manifests/kadalu-operator.yaml | sed -e 's/"no"/"yes"/g' | kubectl apply -f -
​
namespace/kadalu unchanged
serviceaccount/kadalu-operator unchanged
serviceaccount/kadalu-csi-nodeplugin unchanged
serviceaccount/kadalu-csi-provisioner unchanged
serviceaccount/kadalu-server-sa unchanged
customresourcedefinition.apiextensions.k8s.io/kadalustorages.kadalu-operator.storage configured
clusterrole.rbac.authorization.k8s.io/pod-exec unchanged
clusterrole.rbac.authorization.k8s.io/kadalu-operator unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-operator unchanged
deployment.apps/operator configured
```
​
(wait for operator and csi-provisionner pods in `kadalu` namespace get in `Running` state)
​
3. Apply the kadalu CSI-nodeplugin file: https://raw.githubusercontent.com/kadalu/kadalu/0.8.6/manifests/csi-nodeplugin.yaml (optionnaly turn the verbosity to "yes")
​
```
curl -s https://raw.githubusercontent.com/kadalu/kadalu/0.8.6/manifests/csi-nodeplugin.yaml | sed -e 's/"no"/"yes"/g' | kubectl apply -f -
​
clusterrole.rbac.authorization.k8s.io/kadalu-csi-nodeplugin unchanged
clusterrolebinding.rbac.authorization.k8s.io/kadalu-csi-nodeplugin unchanged
daemonset.apps/kadalu-csi-nodeplugin configured
```
​
Wait for the `kadalu-csi-nodeplugin*` pod got all replaced and get in `Running` state: it can take time since there's 1 pod per node and kadalu upgrade them one at a time
​-------------
