### ISSUE TITLE
[RFE] Add support for windows containers

### ISSUE THREAD

**Issue by hunter86bg** [kadalu/kadalu#654]
As Samba supports libgfapi, we can enhance kadalu with windows/CIFS support. Also,we can use ctdb + samba to make it highly available if pod restart is slow compared to ctdb.

**Comment by leelavg** [comment]
- Discussions so far can be found at #518 
- AFAIK, the flow would be Kadalu exposes Samba server, the smb driver project (includes csi proxy to be used on windows node) can be used to create storageClass which can serve PVC requests

**Comment by aravindavk** [comment]
- Create a new container image with Samba and Kadalu/GlusterFS installed.
- To use `libgfapi`, enhancement required in Samba integration code to add `volfile_path` option(Currently it is expecting URL or socket to reach Glusterd to get the Volfile) https://www.samba.org/samba/docs/current/man-html/vfs_glusterfs.8.html
- It is possible to support `vfs objects = glusterfs_fuse` now. Generate the Volfile as required, Mount the Gluster volume and then configure the samba.
- Create new CRD or add option to existing CRD as `samba_export` and then Operator can take care of the above steps. 
- After the setup, IP of the Samba pod to be enabled for external access so that windows client can use the Storage(TBD)

Is Samba support required for a PV or for the Kadalu Storage pool?

**Comment by hunter86bg** [comment]
To be honest, I got no clue which one is needed for windows pods to be able to consume it.

**Comment by leelavg** [comment]
@aravindavk,

- This proposed flow is for supporting external gluster right? Or would it hold true for internal gluster as well?
> Is Samba support required for a PV or for the Kadalu Storage pool?

If we are changing CRD then it'll mostly be on storage pool level and PV level requirement might be hard to fulfil. 

So, we can get away without using SMB driver project? Atleast CSI Proxy is required (anyways windows admin need to make sure of this availability on windows nodes).

**Comment by aravindavk** [comment]
> @aravindavk,
> 
> 
> 
> - This proposed flow is for supporting external gluster right? Or would it hold true for internal gluster as well?

Works for both.

For external, Libgfapi works without any change required in samba layer.

> 
> > Is Samba support required for a PV or for the Kadalu Storage pool?
> 
> 
> 
> If we are changing CRD then it'll mostly be on storage pool level and PV level requirement might be hard to fulfil. 

Mention of CRD is because it involves starting a new pod. Other option is to start smb server in provisioner pod itself so that it can be handled only with Storage class.

> 
> 
> 
> So, we can get away without using SMB driver project? Atleast CSI Proxy is required (anyways windows admin need to make sure of this availability on windows nodes).
