### ISSUE TITLE
Automatically delete subvol folder if pvc gets deleted

### ISSUE THREAD

**Issue by Y0ngg4n** [kadalu/kadalu#761]
Hi it would be nice if you could implement something like a cronjob that deletes all subvol folders that aren´t referenced by any pvc anymore. So if you delete a pvc it will also delete the subvol. It isn´t very handy to allways mount the volume find the directory and delete it by hand. Would be nice if this could be implemented :)

**Comment by leelavg** [comment]
- It wasn't given a much thought I'd guess as that's a good to have rather than must have
- iirc, we are using `shutil.rmtree` (for removing pvc dir) and `os.remove` (for a pvc block file)
- Just curious, what's the need that you find to remove the dir tree with no PVC apart from not having a bunch of sub folders hanging around?

@aravindavk did you think of #748 recently, as you mentioned earlier can we create PVC directly on pool dir?

**Comment by Y0ngg4n** [comment]
@leelavg the problem is for example kubegres. When kubegres failsover it creates a new statefulset with new pvc. Problematic is that the old pvc stays and when you restart it for example 10 times you have 30 pvcs hanging aroud with each a postgres instance. and it it anoying to go into each pvc get the volume and delete the path. It is just an example but would be nice if the path would get automatically deleted when the pvc gets deleted.

**Comment by leelavg** [comment]
@Y0ngg4n 

- then the issue is something different I think, does failing over statefulset also deletes the underlying PVC with data and create a new one?
- what i think might be happening is, as the app is a statefulset k8s isn't sending a DeleteVolume CSI rpc and so the PVC hangs around
- do you know of any other CSI which removes unclaimed PVCs? In your case I feel PVC will still be bound to a PV?

Maybe my assumptions are wrong, pls let me know of any other info I should be aware of.

**Comment by Y0ngg4n** [comment]
@leelavg yes the app does not delete the old pvc but it would be easier to delete the pvc in the dashboard for example and delete also the directories 🤔

**Comment by leelavg** [comment]
- ack, that's the issue. It's not in purview of Kadalu CSI if I've to put it that way.
- Afaic-tell user should invoke PV(C) deletion and that'll trigger CSI rpc call which'll remove the PVC dir in pool, two subdirs above PVC will hang around but that's not a issue to look around as of now (pinged above for that)

**Comment by Y0ngg4n** [comment]
ah ok thank you :)

**Comment by leelavg** [comment]
fixed leaf nodes deletion in #828
