### ISSUE TITLE
Configure monitoring

### ISSUE THREAD

**Issue by amarts** [kadalu/kadalu#8]
Using prometheus, also needs grafana dashboard to view these metrics.

**Comment by amarts** [comment]
Still needed.

**Comment by aravindavk** [comment]
still needed.

**Comment by aravindavk** [comment]
To start with we can start with the following metrics. Metric exporter will run in all Pods as container or as shared process within the container in case accessing required resource is challenge.

* **Storage utilization(Size and inodes)** csi-provisioner will have mounts of all Kadalu Storage Volumes(Hosting Volumes), so it is the best candidate to export all the utilization metrics(`kadalu_storage_count`, `kadalu_storage_health`, `kadalu_storage_capacity_bytes`, `kadalu_storage_capacity_used_bytes`, `kadalu_storage_capacity_free_bytes`, `kadalu_storage_inodes_count`, `kadalu_storage_inodes_used_count`, `kadalu_storage_inodes_free_count` etc)
* **PV utilization** Simple Quota Crawler is anyways doing the crawl and collecting the stat of each subvols/Pvs, This can export the metrics related to the PVs(`kadalu_pv_count`, `kadalu_pv_capacity_bytes`, `kadalu_pv_capacity_used_bytes`, `kadalu_pv_capacity_free_bytes`, `kadalu_pv_inodes_count`, `kadalu_pv_inodes_used_count`, `kadalu_pv_inodes_free_count` etc).
* **Memory, CPU, Uptime and other metrics** Export these metrics for all the processes in Kadalu managed Containers.
* **Heal related metrics** CSI Provisioner or Operator can run `glfsheal` command and export the heal metrics.

Two options to export these metrics to Prometheus:

* Expose single `/metrics` endpoint from Operator. When Prometheus requests the metrics then internally collect from other pods using `kubectl exec`.
* Expose metrics from respective containers itself. Prometheus Server(Prometheus Operator) can collect metrics from these individual exporters by using Pod/Container label.

**Bonus**: `kubectl kadalu storage-health` CLI can be created by consuming these metrics. So that Admins can get the realtime status without using Prometheus or Grafana.

Let us know if any other metrics required other than the ones listed above?

**Comment by sputnik13** [comment]
like the storage-health command idea, not always convenient to bring up grafana for viewing health status

**Comment by aravindavk** [comment]
> Expose single /metrics endpoint from Operator. When Prometheus requests the metrics then internally collect from other pods using kubectl exec.

Little change to this approach. Each containers exposes ReST APIs and Operator will collect from all these containers and exposes a single API.

Operator(`GET /metrics`) -> Collect metrics from all the containers in Kadalu namespace by calling respective ReST APIs(internal APIs).

Advantages:
* Easy to integrate with internal or externally hosted Prometheus server.
* Easily avoid collecting duplicate metrics. Operator can intelligently pick any one storage pod to get the metrics.

Additionally expose `GET /metrics.json` for all non-Prometheus purposes. 

This approach is very similar to [Gluster Metrics Exporter](https://github.com/kadalu/gluster-metrics-exporter) project.

**Comment by leelavg** [comment]
@aravindavk can this issue be closed?

**Comment by leelavg** [comment]
ping @aravindavk ^^, can this be closed?

**Comment by patama8** [comment]
Sorry, if some msail send to you not me anx im mever contact with you noting that company for my husband and im not want to get mofe problem with him so fucking tried for lady in pattaya ThailandThank you so muchPatamaเมื่อ 21 ม.ค. 2023 11:43 น. "stale[bot]" ***@***.***> เขียนว่า
Closed #8 as completed.
