### ISSUE TITLE
[RFE]: Helm vs Jinja2

### ISSUE THREAD

**Issue by Timoses** [kadalu/kadalu#850]
**Is your feature request related to a problem? Please describe.**
It's no fun [manually syncing Jinja2-generated manifests and helm chart files](https://github.com/kadalu/kadalu/pull/848#issuecomment-1157739688).

**Describe the solution you'd like**
Why not separate into:
* `templates/` directory contains only templated manifests rolled out by the operator (or kadalu controll plane)
* The rest goes into Helm. `manifests/` files can be generated via `helm template` from there.

**Describe alternatives you've considered**
Attempting to generate helm chart template files from jinja2. I don't see the bonus though. What's the benefit of having a jinja2 templated resource when it is not used in a programmatic python context?

**Additional context**
Just a suggestion to make it a bit easier to handle manifest generation.
I think it makes sense to differentiate between resources rolled out by Kadalu control plane (where jinja2 makes sense, haven't heard of a helm2 python library...) and the actual manifests deployed by users themselves.

**Comment by leelavg** [comment]
> Attempting to generate helm chart template files from jinja2.
- No we are not generating helm chart template from jinja2 manifests

General Info:
1. `templates/` contain all the Jinja2 files either user deployed or kadalu deployed
2. some of the files here will go into `manifests/` dir after generation in a PR and to releases pages for direct deployments via `curl`
3. user generally deploys `kadalu-operator*.yaml` and `csi-nodeplugin-*.yaml` (the separation in here is to ease some upgrade scenarios)
4. every other file will be generated at runtime by kadalu-operator and deployed to the cluster (general reconcile loop, uses direct files rather than constructing k8s objects)

Helm & Jinja2:
1. there was an ask from users to provide helm deployments and helm folder with required templates was created
2. we follow only minimal guidelines from helm world, just that when user runs helm command to install from tar file the deployment should be successful
3. now coming to testing the changes that happens to operator code, that'll be realised in multiple places, yaml manifests, kadalu cli, helm templates and we always test manifests, conditionally cli if there are any changes
4. the one left out is helm, b/n spinning up a new minikube cluster in CI and testing helm alone we take a diff of `manifests` and template generated from `helm template` and verify no changes (well, openshift verification is an outlier, will take a re-look if needed)
5. at the end of the day helm also generates yaml manifests and if can make sure that manifests generated from jinja2 and helm are matching then testing helm isn't strictly necessary

For syncing templates:
1. although it's manual the required effort is simple, where ever the lines are modified in `templates/` dir make corresponding modification in `helm/kadalu` folder

Pardon the exhaustive answer, I just want to state the problem that we intend to solve and one way of solving it. If others can pitch in and provide an alternative workable/working solution we don't have any issue in changing current workflow 😄

**Comment by aravindavk** [comment]
Jinja templates are used in other places like Volfile generation and a few other places. 

We can shift to use Helm templates only for Kubernetes specific yaml files and continue using Jinja for other Gluster specific templates(Volfiles). Instead of complicating the current Operator code by bringing more dependencies, I like the idea of generating the Helm templates itself from the Jinja Templates.

**Comment by leelavg** [comment]
> Helm templates itself from the Jinja Templates.
- I'll refactor user deployable manifests to be generated from helm
- kadalu deployable manifests will be untouched 

Is that fine @aravindavk ?

**Comment by Timoses** [comment]
> For syncing templates:
> 
>  1. although it's manual the required effort is simple, where ever the lines are modified in `templates/` dir make corresponding modification in `helm/kadalu` folder

It is possible. However, it is cumbersome. One needs to analyse in which order Helm parses the template files (which is not alphabetical xD). It might sound trivial, but it's an effort that can be spared on our valuable dev brains :).

---

> Instead of complicating the current Operator code by bringing more dependencies, I like the idea of generating the Helm templates itself from the Jinja Templates.

Sounds compelling, though I wouldn't recommend using two templating engines piped into one another. It'll end up with only the last pipe producing real valuable output while the previous would have to be sanitized to remove the templating expressions from the other templating engine.

---

I haven't thought of the kadalu cli tool. Does it offer deploying Operator and CSI nodeplugins (by throwing manifests at a k8s cluster)? If so and it currently has a dependency on the `templates/` dir, it could be changed to use helm to construct its manifests.

---
All in all, I'd see it as a plus to have this clear separation between Operator deployed manifests (`templates/` dir) and user/adminstrator-deployed manifests (via Helm or via auto-generated and released manifests with `helm template` in makefile).

**Comment by leelavg** [comment]
> but it's an effort that can be spared
- agreed

> by throwing manifests at a k8s cluster
- nope, CLI tool is stateless, it reaches out to github releases if local option isn't provided. So, no issues.

> have this clear separation
- yep, that's the final deal. I think it'll be pretty straightforward
- iirc, `helm template` couldn't generate namespace yaml, apart from that every change of user deployable content will go to `helm/kadalu` folder alone and we use `helm template` in `gen-manifest` target
- anyways, I'll take a look (mostly on Monday)
