### ISSUE TITLE
Storage Type with dynamic replica count?

### ISSUE THREAD

**Issue by demern** [kadalu/kadalu#896]
I have a use case where a number of K8s pods deployed across multiple (specified) nodes need access to a shared pure replicate Gluster volume. In general, the number of nodes involved can be anywhere from 1 to 32, and can shrink or expand dynamically. We also have a requirement that, when removing or adding nodes/pod instances, the instances on unaffected nodes must stay up and available. Generally speaking, storage bricks must be co-located within the same set of nodes that the pods are deployed on; there are no dedicated storage nodes.

We would like to take advantage of the HA benefits of pure replicate volumes as much as possible; when the number of nodes is 3+, the volume should be replica 3. When the node set shrinks to 2, the volume would still remain replica 2 (or, perhaps, replica 3 arbiter 1, using separate special nodes as arbiter-only nodes...still working this out). And in the 1-node case, we would like to use a replica 1 volume...the key requirement is that the pods consuming this storage can't be restarted/re-deployed, IE we cannot change the PV/PVC attached to them.

Vanilla Gluster storage seems to be happy to change the replica count of existing volumes while leaving volumes online as part of brick add/remove operations. However, looking at software based on Gluster that advertises close integration with K8s, such as Kadalu and Heketi, I don't see similar functionality. In Kadalu's case, as far as I can tell, you have to pick a replica count and stick with it when creating a PV for use with K8s. This doesn't seem to fit our use case, since for example if we use a replica 3 PV, it won't function when moving down to the <3 node case. And vice-versa, using replica 1 or 2 doesn't fit our HA needs in the 3+ node case. We can't transition between PVs with different replica counts due to the requirement that running pods can't be stopped and re-deployed with modified PVCs.

So, hence the title of this issue...it would be great if there was a way to leverage similar functionality that's available with vanilla Gluster storage and have Kadalu dynamically change the replica count of a single volume as the number of nodes available for hosting storage in the deployment shrinks/expands. My questions then are:

1.) Does such functionality exist in Kadalu?/Is it planned or feasible?
2.) If it does not exist, are there any recommendations on achieving a similar goal with Kadalu/K8s? Or do I have to come up with my own solution that uses lower-level Gluster functionality?

Sorry for the the essay-length question...I struggled to find a more succinct way to explain myself. And thank you to anyone who reads and responds!

**Comment by leelavg** [comment]
> there are no dedicated storage nodes.
- this sums up the gist for first para, doesn't it?

> We would like to take advantage of the HA benefits of pure replicate volumes...
- iiuc, the ask from this para is impossible atm, not in-terms of scaling but in-terms of data healing + checks and balances for scaling
- Kadalu operator isn't sophisticated enough for performing these activities (if only we can convince other maintainers to re-write Kadalu Operator to reach feature-parity with golang based operators)
- having said that, this is a huge effort/ask for this project as of now

> Vanilla Gluster storage seems to be happy 
- then you can continue to use that, have Gluster Storage out of k8s and use Kadalu CSI to have storage available to k8s workloads

> running pods can't be stopped 
- remember, in the worst case, any fuse based Filesystem may become unavailable if the underlying nodeplugin reboots
- again, this is the extreme case and your workloads shouldn't assume 100% storage uptime

> Kadalu dynamically change the replica count of a single volume as the number of nodes available
- the solution can be created with some effort however it's not trivial considering all other enhancements going around in kadalu project, this takes good enough engineering effort

> 1.) Does such functionality exist in Kadalu?/Is it planned or feasible?
- only bits & pieces exist however a cohesive flow can't be offered now

> 2.) If it does not exist, are there any recommendations on achieving a similar goal with Kadalu/K8s? Or do I have to come up with my own solution that uses lower-level Gluster functionality?
- as mentioned earlier, you can use External Gluster managed by you (/your ops team) and use Kadalu CSI for k8s workloads

> Sorry for the the essay-length question
- hmm, I kinda put off twice from replying not because of it's length but because of our availability and finally able to put up a response.

**Comment by demern** [comment]
Thank you very much for the reply. This seems to confirm my suspicion that Kadalu doesn't support this exact use case right now. I understand that adding such support is a large undertaking/not the highest priority for your project--just wanted to double-check before spinning my own solution using base Gluster functionality. I will definitely look into using Kadalu CSI with whatever I come up with, thanks for the tip.

With that in mind, I will close this, thanks.

**Comment by leelavg** [comment]
@demern I believe you overlooked the solution that Kadalu provides for using External Gluster storage already rather than rolling up your own.

Have a look at https://kadalu.github.io/docs/k8s-storage/devel/external-gluster-storage/, it's already documented.

**Comment by demern** [comment]
I'll also look into that. I guess what I meant by 'rolling my own' was that it's up to me to create/manage the volumes using Gluster, and also manage any dynamic changes in replica count of the volume myself, even if I make use of the Kadalu operator and 'external' storage type, right?
